### ISSUE TITLE
About About database credentials for setup

### ISSUE THREAD

**Issue by mozgbrasil** [FloWebDev/starter-kit-magento1-docker#1]
Good morning my friends

I'm testing your project and I'm not able to connect to the database

Can you tell me which data I should use for Magento setup

![Captura de tela de 2022-01-27 19-59-37](https://user-images.githubusercontent.com/17202780/151457539-e9c63f97-a210-44f1-ac7d-eec536d48f72.png)

Thanks in advance to everyone who can contribute.

**Comment by FloWebDev** [comment]
Hello,

Try with 127.0.0.1 instead of localhost for database Host.

**Comment by FloWebDev** [comment]
No don't try with localhost or 127.0.01, try "mysql".

**Comment by mozgbrasil** [comment]
Good morning my friends
I was able to install Magento in local environment
Thanks for listening
